title: "Jeffrey Rivor's coding blog"
timezone: America/Los_Angeles
exclude: ["LICENSE"]
permalink: pretty
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      author: "Jeffrey Rivor"
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title
feed:
  excerpt_only: true
markdown: GFM
readme_index:
  remove_orignals: true
titles_from_headings:
  strip_title: true
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-sitemap
