title: Jeffrey Rivor's coding blog
author:
  name: Jeffrey Rivor
description: >
  Principal Software Engineer at Microsoft since 2015.
  Opinions are my own.
show_excerpts: true

timezone: America/Los_Angeles
exclude: ["LICENSE"]

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/jeffreyrivor
    - platform: linkedin
      user_url: https://www.linkedin.com/in/jeffrey-r-9300913a

permalink: pretty
defaults:
  - scope:
      path: "*.html"
      type: pages
    values:
      layout: page
  - scope:
      path: /index.html
      type: pages
    values:
      layout: home
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Jeffrey Rivor
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title
header_pages:
  - posts.html
feed:
  excerpt_only: true
markdown: GFM
readme_index:
  remove_orignals: true
titles_from_headings:
  strip_title: true
  collections: true
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-octicons
  - jekyll-sitemap
