title: Jeffrey Rivor's blog
author:
  name: Jeffrey Rivor
description: >
  Principal Software Engineer at Microsoft since 2015.
  Opinions are my own.
show_excerpts: true

lang: en-US
timezone: America/Los_Angeles

# Jekyll [3.3, 4) requires user-configured excludes to manually prepend default excludes
exclude:
# defaults
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
# additions
- LICENSE
- .github/
- .vs/
- .vscode/

theme: minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/jeffreyrivor
    - platform: linkedin
      user_url: https://www.linkedin.com/in/jeffrey-r-9300913a

permalink: pretty
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Jeffrey Rivor
      lang: en-US
  - scope:
      path: "*.html"
      type: pages
    values:
      layout: page
  - scope:
      path: "README.md"
    values:
      list_title: All Posts
header_pages:
  - posts.html
  - japan.html
feed:
  excerpt_only: true
readme_index:
  remove_orignals: true
titles_from_headings:
  strip_title: true
  collections: true

future: true # defaults from github-pages
jailed: false # defaults from github-pages
lsi: false # defaults from github-pages
highlighter: rouge # defaults from github-pages
markdown: kramdown # defaults from github-pages
kramdown: # defaults from github-pages
  input: GFM
  hard_wrap: false
  gfm_quirks:
    - paragraph_end
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    default_lang: plaintext
  template: ""
gist: # defaults from github-pages
  noscript: false
sass: # defaults from github-pages for production
  style: compressed
safe: true # defaults from github-pages
whitelist: # defaults from github-pages
  - jekyll-avatar
  - jekyll-coffeescript
#  - jekyll-commonmark-ghpages removed due to incompatibility with Jekyll 4
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-optional-front-matter
#  - jekyll-paginate removed due to no active development (switch to v2 if needed, but needs minima theme support)
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
#  - jekyll-remote-theme removed for using theme gem
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
