title: Jeffrey Rivor's blog
author:
  name: Jeffrey Rivor
description: >
  Principal Software Engineer at Microsoft since 2015.
  Opinions are my own.
show_excerpts: true

timezone: America/Los_Angeles

# Jekyll [3.3, 4) requires user-configured excludes to manually prepend default excludes
exclude:
# defaults
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
# additions
- LICENSE
- .vs/
- .vscode/

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/jeffreyrivor
    - platform: linkedin
      user_url: https://www.linkedin.com/in/jeffrey-r-9300913a

permalink: pretty
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Jeffrey Rivor
  - scope:
      path: "*.html"
      type: pages
    values:
      layout: page
  - scope:
      path: "README.md"
    values:
      list_title: All Posts
header_pages:
  - posts.html
  - japan.html
feed:
  excerpt_only: true
markdown: GFM
readme_index:
  remove_orignals: true
titles_from_headings:
  strip_title: true
  collections: true
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-octicons
  - jekyll-sitemap
