title: "Jeffrey Rivor's coding blog"
timezone: America/Los_Angeles
exclude: ["LICENSE"]
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      author: "Jeffrey Rivor"
markdown: GFM
readme_index:
  remove_orignals: true
plugins:
  - jekyll-octicons
