# frozen_string_literal: true

source "https://rubygems.org"

gem "github-pages-health-check", "= 1.17.9"
gem "jekyll", "= 3.9.3"
gem "jekyll-avatar", "= 0.7.0"
gem "jekyll-coffeescript", "= 1.1.1"
gem "jekyll-default-layout", "= 0.1.4"
gem "jekyll-feed", "= 0.15.1"
gem "jekyll-gist", "= 1.5.0"
gem "jekyll-github-metadata", "= 2.13.0"
gem "jekyll-include-cache", "= 0.2.1"
gem "jekyll-mentions", "= 1.6.0"
gem "jekyll-octicons", "~> 19.7"
gem "jekyll-optional-front-matter", "= 0.3.2"
gem "jekyll-paginate", "= 1.1.0"
gem "jekyll-readme-index", "= 0.3.0"
gem "jekyll-redirect-from", "= 0.16.0"
gem "jekyll-relative-links", "= 0.6.1"
gem "jekyll-remote-theme", "= 0.4.3"
gem "jekyll-sass-converter", "= 1.5.2"
gem "jekyll-seo-tag", "= 2.8.0"
gem "jekyll-sitemap", "= 1.4.0"
gem "jekyll-titles-from-headings", "= 0.5.3"
gem "jemoji", "= 0.12.0"
gem "kramdown", "= 2.3.2"
gem "kramdown-parser-gfm", "= 1.1.0"
gem "liquid", "= 4.0.4"
gem "mercenary", "~> 0.3"
gem "nokogiri", ">= 1.13.6", "< 2.0"
gem "rouge", "= 3.26.0"
gem "terminal-table", "~> 1.4"
gem "tzinfo-data", "~> 1.2023", platforms: :windows
gem "webrick", "~> 1.8"
